### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by DoxaLogosGit**
I did merge in your latest changes with this branch.  I'd hate for it to fall off the radar, so here it is if you want to merge it into mainline.  I think the only issue is the sitesettings.py, since I had to point it at the mysql container host name and not localhost for docker-compose to use two separate containers.  Feel free to change it back to localhost, but it will break the docker compose setup.  If you put the mysql  server back into the same container as the extended code and forget docker compose,  it will work again with "localhost" in sitesettings.py.

### CODE REVIEW

**Comment by DrFriendless** [comment]
I'm not really adept at reading the diffs yet... it looks like you've added a lot of .pyc files still? Or did you delete ones that I put in there?

**Comment by DoxaLogosGit** [comment]
I deleted the .pyc files a while back, since they really don't need to be in a VCS and are generated at runtime if changed.  Also added a ".gitignore" file, so git won't pick up the status of .pyc files and try to add them to the repo.  I think a new .pyc snuck back in from merging back with your latest changes.

**Comment by DrFriendless** [comment]
Yep, I saw that new one try to sneak in - it's because I ran up the views with flask, to see what happened. I told git I didn't want it committed, and it said oh but it followed me home it's so cute blah blah blah and apparently ignored me. Git and I have some learning to do together.

**Comment by DoxaLogosGit** [comment]
I think the .gitignore will help that in the future.

**Pull request merged**
