### PR TITLE
adding context managers on opens

### PR DESCRIPTION
**Pull request by DoxaLogosGit**
Thought I would help tidy up a bit.  I found it strange where you call "file" constructor instead of open around line 883 of readMetadata in populateFiles.py.  I think "with" will work with it, but I've never seen that used before.

I'm also looking into MySqlDB and see if they use context managers.

### CODE REVIEW

**Comment by DrFriendless** [comment]
BTW I believe "file" is a more modern version of "open". I have been trying to get my changes committed this evening and have made an awful mess of things. I think I'm back down to 2 sensible branches at the moment.

**Comment by DrFriendless** [comment]
My understanding is that somehow I should be able to get your changes into my repository at home without having to first merge them into master on github. However I have no idea how to do that. Got any tips?

**Comment by DoxaLogosGit** [comment]
I think this might help.  My first thought is remote branches:

http://stackoverflow.com/questions/5884784/how-to-pull-remote-branch-from-somebody-elses-repo

Make a remote branch from my git repo. https://github.com/jgatkinsn/ExtendedStats

**Comment by DoxaLogosGit** [comment]
Also, python docs say about using "file" constructor:

"When opening a file, it’s preferable to use open() instead of invoking this constructor directly. file is more suited to type testing (for example, writing isinstance(f, file))."

file() is gone in Python 3.

**Comment by DrFriendless** [comment]
OK, I think I did it. The theory of git is much nicer than the practice of git.

**Comment by DoxaLogosGit** [comment]
Ha, too true.

**Pull request merged**
